spring.application.name=conta-service

# porta do servidor (definido 8081 para evitar conflito com outros serviços)
server.port=8081

# credenciais e endereço do RabbitMQ
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest